version: 2

defaults: &defaults
 working_directory: /tmp/project
 docker:
   - image: arcanemagus/atom-docker-ci:stable

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Download Atom test script
          command: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
      - run:
          name: Make Atom script executable
          command: chmod u+x build-package.sh
      # Restore node_modules from the last build
      - restore_cache:
          keys:
          # Get latest cache for this package.json
          - v2-dependencies-{{ checksum "package.json" }}
          # Fallback to the last available cache
          - v2-dependencies
      # Save project state for next steps
      - persist_to_workspace:
          root: /tmp
          paths:
            - project

  stable:
    <<: *defaults
    steps:
      # Restore project state
      - attach_workspace:
          at: /tmp
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: Install Clang
          command: sudo apt-get --assume-yes --quiet --no-install-suggests --no-install-recommends install clang
      # Fire up a VFB to run Atom in
      - run:
          name: Create VFB for Atom to run in
          command: /usr/bin/Xvfb $DISPLAY -ac -screen 0 1280x1024x16
          background: true
      - run:
          name: Atom test
          command: ./build-package.sh
      # Cache node_modules
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

  beta:
    <<: *defaults
    image: arcanemagus/atom-docker-ci:beta
    steps:
      # Restore project state
      - attach_workspace:
          at: /tmp
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: Install Clang
          command: sudo apt-get --assume-yes --quiet --no-install-suggests --no-install-recommends install clang
      # Fire up a VFB to run Atom in
      - run:
          name: Create VFB for Atom to run in
          command: /usr/bin/Xvfb $DISPLAY -ac -screen 0 1280x1024x16
          background: true
      - run:
          name: Atom test
          command: ./build-package.sh


  release:
    <<: *defaults
    steps:
      # Restore project state
      - attach_workspace:
          at: /tmp
      - run:
          name: semantic-release
          command: npx semantic-release
      # Cache node_modules
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  test_package:
    jobs:
      - checkout_code
      - stable:
          requires:
            - checkout_code
      - beta:
          requires:
            - checkout_code
      - release:
          requires:
            - stable
          filters:
            branches:
              only: master
